docs:
  - changed-files:
    - any-glob-to-any-file: ["docs/**", "*.md"]

workflows:
  - changed-files:
    - any-glob-to-any-file: '.github/**'

configurator:
  - changed-files:
    - any-glob-to-any-file: 'Source/common/SNTConfigurator.*'

lang/objc:
  - changed-files:
    - any-glob-to-any-file: "**/*.m"

lang/objc++:
  - changed-files:
    - any-glob-to-any-file: "**/*.mm"

lang/swift:
  - changed-files:
    - any-glob-to-any-file: "**/*.swift"

comp/common:
  - changed-files:
    - any-glob-to-any-file: "Source/common/**"

comp/gui:
  - changed-files:
    - any-glob-to-any-file: "Source/gui/**"

comp/santabundleservice:
  - changed-files:
    - any-glob-to-any-file: "Source/santabundleservice/**"

comp/santactl:
  - changed-files:
    - any-glob-to-any-file: "Source/santactl/**"

comp/santad:
  - changed-files:
    - any-glob-to-any-file: "Source/santad/**"

comp/santametricservice:
  - changed-files:
    - any-glob-to-any-file: "Source/santametricservice/**"

comp/santasyncservice:
  - changed-files:
    - any-glob-to-any-file: "Source/santasyncservice/**"

