name: 🚀 Feature Request / Enhancement
description: Request a new feature or enhancement
labels: ["enhancement"]
type: "Feature"

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to request a feature or ask a question!
        Please provide as much detail as possible to help us understand your needs.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: Brief summary of your feature request or question
      placeholder: What would you like to see or know?
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a detailed description of your feature request or question
      placeholder: |
        - What problem does this solve?
        - Why is this important to you?
        - Any additional context, examples, or screenshots?
    validations:
      required: true
