name: 💡 FAA/CEL Cookbook Idea
description: Submit a use case idea to add to the CEL and FAA cookbook
labels: ["cookbook", "enhancement"]
type: "Task"

body:
  - type: markdown
    attributes:
      value: |
        Thanks for sharing your idea for the cookbook! This is a community supported collection of ideas to help  Santa users enhance the security of their fleets.

  - type: dropdown
    id: feature_type
    attributes:
      label: Feature Type
      description: Which feature does this use case relate to?
      options:
        - FAA (File Access Authorization)
        - CEL (Common Expression Language)
    validations:
      required: true

  - type: input
    id: use_case_title
    attributes:
      label: Use Case
      description: A concise title for your use case
      placeholder: Brief, descriptive title for your use case
    validations:
      required: true

  - type: textarea
    id: use_case_description
    attributes:
      label: Detailed Use Case Description
      description: Provide a comprehensive description of your use case
      placeholder: |
        Please describe information such as:
        - The business problem or opportunity
        - How this use case would benefit security
        - Any specific requirements or constraints
        - What are the limitations of your current approach?
    validations:
      required: true

  - type: textarea
    id: use_case_policy
    attributes:
      label: Policy
      description: Provide the complete FAA/CEL policy
      placeholder: |
        Provide either the FAA rule dictionary or CEL expression
    validations:
      required: true
