// Test credentials for NATS integration tests
// Generated by nsc for test-machine-12345

#ifndef TEST_CREDENTIALS_H
#define TEST_CREDENTIALS_H

// JWT Token (subscribe only)
#define TEST_JWT                                                                                   \
  @"eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ."                                               \
  @"eyJqdGkiOiJVWUNBWjRFWkw2TEJJQVVMNUZKT0lYT0ZSRUVCN0lSVEhYR0pKTUMyVkZGWllDRFZTR09RIiwiaWF0IjoxN" \
  @"zYxMzU1NDIzLCJpc3MiOiJBRE40R1VISEtNR01MMkQyQURFTFBVWUVGRjNRWU5JNERWTjZGNDNKUFA2R0k3VjRTVVlTSl" \
  @"RCNCIsIm5hbWUiOiJ0ZXN0LW1hY2hpbmUtMTIzNDUiLCJzdWIiOiJVQ043WTQ1VzVLTkE3V01ZTVdSQVVRSkRDSEVOQ1o" \
  @"3N1BSWVNCMkhYSENNUFRBNlBXRVZMVVRNTyIsIm5hdHMiOnsicHViIjp7fSwic3ViIjp7ImFsbG93IjpbInNhbnRhLWNs" \
  @"aWVudHMiLCJzYW50YS4qIiwid29ya3Nob3AiXX0sInJlc3AiOnsibWF4IjoxLCJ0dGwiOjB9LCJzdWJzIjotMSwiZGF0Y" \
  @"SI6LTEsInBheWxvYWQiOi0xLCJ0eXBlIjoidXNlciIsInZlcnNpb24iOjJ9fQ.fWGCRcIJ4Dl_89yA5BxtKEmt_A8_"    \
  @"YfuVFh_QNDOoC1MA6z78jdon1RPSseUSGbYJyFwc5qzzERL9f0oqwXkZBg"

// NKEY Seed
#define TEST_NKEY @"SUACBNSCZDJFQNXSNUMNMPHN7UY5AWS42E6VMQXVTKCU2KJYBR75MVDPJQ"

// Publisher JWT Token (publish and subscribe)
#define TEST_PUBLISHER_JWT                                                                         \
  @"eyJ0eXAiOiJKV1QiLCJhbGciOiJlZDI1NTE5LW5rZXkifQ."                                               \
  @"eyJqdGkiOiJKN0pYVUdaWE1CSExRUzNTWFFYVE1INDVUWFdOMjJONkRHWDNNQUU1RFU0VlFDNlJUNE1BIiwiaWF0IjoxN" \
  @"zYxMzkzMTI1LCJpc3MiOiJBRE40R1VISEtNR01MMkQyQURFTFBVWUVGRjNRWU5JNERWTjZGNDNKUFA2R0k3VjRTVVlTSl" \
  @"RCNCIsIm5hbWUiOiJ0ZXN0LXB1Ymxpc2hlciIsInN1YiI6IlVCM1ZDTFRRSVMyWklPUjRNRzdZSFFQNkU2Q1NQUVA0Nkx" \
  @"QNjNVUUFHNldITU40WUJJS0VPTkIyIiwibmF0cyI6eyJwdWIiOnsiYWxsb3ciOlsic2FudGEuKiJdfSwic3ViIjp7ImFs" \
  @"bG93IjpbInNhbnRhLioiXX0sInN1YnMiOi0xLCJkYXRhIjotMSwicGF5bG9hZCI6LTEsInR5cGUiOiJ1c2VyIiwidmVyc" \
  @"2lvbiI6Mn19."                                                                                  \
  @"Cp6r2Nw6ai7jR7twR2POG35IHlszAIR8hEasJA7F7EM7qm4naO2EST5dFh85efPPk3kMAi7bS9TyptI1YvEVAA"

// Publisher NKEY Seed
#define TEST_PUBLISHER_NKEY @"SUAHTEEWVEQ72TBSE5ZRCCALOU57HKPOLWDLZGBHZB6RMAPOD5OI4KNAYM"

// Machine ID for testing
#define TEST_MACHINE_ID @"test-machine-12345"

// Server configuration
#define TEST_SERVER @"localhost"
#define TEST_PORT 443

#endif  // TEST_CREDENTIALS_H
