package(
    default_visibility = ["//visibility:public"],
)

licenses(["notice"])

filegroup(
    name = "santa_dev",
    srcs = ["Santa_Dev.provisionprofile"],
)

filegroup(
    name = "daemon_dev",
    srcs = ["Santa_Daemon_Dev.provisionprofile"],
)
