#!/bin/bash

# If the target volume is not /, do nothing
[[ $3 != "/" ]] && exit 0

/bin/launchctl remove com.northpolesec.santa.migration || true
/bin/rm -rf /Library/Caches/com.northpolesec.santa

exit 0
