load("@rules_cc//cc:defs.bzl", "objc_library")

package(default_visibility = ["//visibility:public"])

licenses(["notice"])

objc_library(
    name = "SNDFilterConfigurationHelper",
    srcs = ["SNDFilterConfigurationHelper.mm"],
    hdrs = ["SNDFilterConfigurationHelper.h"],
)
