title: Santa
remote_theme: pmarsceill/just-the-docs

nav_sort: case_insensitive

back_to_top: true
back_to_top_text: "Back to top"

gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/northpolesec/santa"
gh_edit_branch: "main"

plugins:
    - jekyll-redirect-from

callouts:
  warning:
    title: Warning
    color: red
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
