import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

const sidebars: SidebarsConfig = {
  // Generate a sidebar from the docs folder structure.
  mainSidebar: [{ type: "autogenerated", dirName: "." }],
};

export default sidebars;
