name: Process PRs

on:
  - pull_request_target

jobs:
  labels:
    name: Labelers
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4.2.2
        with:
          sparse-checkout: .github

      - name: Apply Labels
        uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # ratchet:actions/labeler@v5
        with:
          configuration-path: .github/labeler-pr.yml

      - name: Apply Size Labels
        uses: codelytv/pr-size-labeler@1c3422395d899286d5ee2c809fd5aed264d5eb9b # ratchet:codelytv/pr-size-labeler@v1.10.2

